"""Format an agent-facing suggestion note for posting into a ticket."""

from zammad_agent.pipeline.classify import Classification
from zammad_agent.pipeline.respond import Draft

_HEADER = "AI SUGGESTION - not sent to the customer"

_UNGROUNDED_WARNING = (
    "WARNING: no knowledge base article supported this reply. The draft below "
    "is the model's general knowledge, not company policy. Verify every "
    "specific claim - timeframes, prices, procedures - before using it."
)


def format_suggestion_note(
    classification: Classification, draft: Draft, model: str
) -> str:
    """Render a suggestion as plain text for an internal Zammad note.

    Written for an agent skimming a ticket, so the warning comes before the
    draft. An agent who reads the reply first has already started trusting it
    by the time they reach a caveat underneath.
    """
    lines = [_HEADER, ""]

    if not draft.grounded:
        lines += [_UNGROUNDED_WARNING, ""]

    lines += [
        f"Intent:     {classification.intent}",
        f"Confidence: {classification.confidence:.2f}"
        + (f" (votes: {classification.votes})" if classification.votes else ""),
        f"Grounded:   {'yes' if draft.grounded else 'NO'}",
    ]

    if draft.sources:
        lines.append(f"Sources:    {', '.join(draft.sources)}")
    if draft.missing_information:
        lines.append(f"Gaps:       {draft.missing_information}")

    lines += ["", "--- suggested reply ---", draft.text, "--- end ---", ""]
    # Named so an agent can tell which model produced a bad suggestion, and so
    # notes from before a model change are identifiable afterwards.
    lines.append(f"Generated by {model}. Review before sending.")

    return "\n".join(lines)
